from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
DATASET_DIR = PROJECT_ROOT / "dataset"
MODELS_DIR = PROJECT_ROOT / "models"
EXPORTS_DIR = PROJECT_ROOT / "exports"
DATABASE_PATH = PROJECT_ROOT / "attendance.xlsx"

YOLO_WEIGHTS_PATH = MODELS_DIR / "yolov8-face.pt"
RECOGNITION_MODEL_PATH = MODELS_DIR / "recognizer.keras"
LABEL_MAP_PATH = MODELS_DIR / "label_map.json"
RECOGNITION_METADATA_PATH = MODELS_DIR / "recognition_metadata.json"

RECOGNITION_BACKBONES = ("mobilenetv2", "efficientnetb0", "vgg16")

FACE_INPUT_SIZE = (224, 224)

DEFAULT_DETECTION_CONFIDENCE = 0.5
DEFAULT_RECOGNITION_CONFIDENCE = 0.80

DEFAULT_CAMERA_INDEX = 0
DEFAULT_CAPTURE_SAMPLE_COUNT = 25

CAPTURE_MIN_FACE_AREA_RATIO = 0.12
CAPTURE_MAX_FACE_AREA_RATIO = 0.55
CAPTURE_MIN_EDGE_MARGIN_RATIO = 0.05

DEFAULT_ADMIN_USERNAME = "admin@attendance.local"
DEFAULT_ADMIN_PASSWORD = "Admin@123"